export const SUPERPOWERS = [
  "💪 Super Strength",
  "🧠 Super Intelligence",
  "🏃 Super Speed",
  "🦵 Super Agility",
  "🏋️ Super Endurance",
  "🛡️ Super Durability",
  "🚑 Super Healing",
  "💪 Super Stamina",
  "👁 Super Senses",
  "👁 Super Sight",
  "🎵 Super Hearing",
  "🧹 Super Smell",
  "🍽️ Super Taste",
  "👉 Super Touch",
  "✈️ Super Flight",
  "🤚 Super Telekinesis",
  "🌀 Super Teleportation",
  "⏰ Super Time Travel",
  "👻 Super Invisibility",
  "🐍 Super Shape-Shifting",
  "🔥 Super Energy Manipulation",
  "🛡️ Super Force Field",
  "☁️ Super Weather Control",
  "🌈 Super Reality Warping",
  "🧠 Super Mind Control",
  "🎩 Super Illusion",
  "🔲 Super Duplication",
  "📏 Super Size-Shifting",
  "🕰️ Super Age-Shifting",
  "🌋 Super Elemental Control",
  "❄️ Super Ice Manipulation",
  "🔥 Super Fire Manipulation",
  "💦 Super Water Manipulation",
  "🌍 Super Earth Manipulation",
  "🌬️ Super Air Manipulation",
  "⚡ Super Electricity Manipulation",
  "🔩 Super Metal Manipulation",
  "🌱 Super Plant Manipulation",
  "🐾 Super Animal Manipulation",
  "🔋 Super Energy Absorption",
  "💪 Super Density Control",
  "🌎 Super Gravity Control",
  "🎵 Super Sound Manipulation",
  "🌟 Super Light Manipulation",
  "🔮 Super Magic",
];

export const dateFormatter = new Intl.DateTimeFormat("en-US", {
  dateStyle: "medium",
});
